--- #YAML:1.0
name:                DBIx-DBSchema
version:             0.34
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    DBI:                           0
    FreezeThaw:                    0
    Storable:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
